-- FIRST THURSDAY BEFORE END OF NEXT MONTH (END OF NEXT MONTH IS NOT EXCLUDED/INCLUDED) WITH PL/SQL
DECLARE
    V_DATE_01 DATE := TO_DATE('25082021' ,'DDMMYYYY');
    V_START_DATE DATE;
    V_END_DATE DATE;
    V_RESULT_DATE DATE; -- END OF NEXT MONTH IS INCLUDED
    V_RESULT_DATE2 DATE; -- END OF NEXT MONTH IS NOT INCLUDED
BEGIN
    V_START_DATE := TRUNC(ADD_MONTHS(V_DATE_01,1),'MONTH');
    V_END_DATE := LAST_DAY(ADD_MONTHS(V_DATE_01,1));
    WHILE V_START_DATE <= V_END_DATE -- BEGINS FROM FIRST DAY OF NEXT MONTH (ALSO IT IS POSSIBLE TO START 3RD WEEK START)
    LOOP

        IF TO_CHAR(V_START_DATE ,'D') = 5 THEN -- IT STARTS COUNTING FROM SUNDAY
            V_RESULT_DATE := V_START_DATE; -- WHEN IT FINDS IT IS THURSDAY IT ASSINGS VALEUE TO V_RESULT_DATE
        END IF;
        
        IF TO_CHAR(V_START_DATE ,'D') = 5 AND V_START_DATE != LAST_DAY(V_START_DATE) THEN
            V_RESULT_DATE2 := V_START_DATE; -- WHEN IT FINDS IT IS THURSDAY IT ASSINGS VALEUE TO V_RESULT_DATE2
        END IF;
        
        V_START_DATE := V_START_DATE + 1;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('INPUT DATE >> ' || V_DATE_01);
    DBMS_OUTPUT.PUT_LINE('V_RESULT_DATE >> ' || V_RESULT_DATE);
    DBMS_OUTPUT.PUT_LINE('V_RESULT_DATE2 >> ' || V_RESULT_DATE2);
END;
/




-- IF WE WANT TO DEFINE SPECIFIC WEEKDAY
DECLARE
    V_DATE_01 DATE := TO_DATE('17072021' ,'DDMMYYYY');
    V_START_DATE DATE;
    V_END_DATE DATE;
    V_RESULT_DATE DATE; -- END OF NEXT MONTH IS INCLUDED
    V_RESULT_DATE2 DATE; -- END OF NEXT MONTH IS NOT INCLUDED
    V_WEEKDAY_INPUT VARCHAR2(9) := 'TUESDAY'; -- THIS VARIABLE SHOULD BE FILLED BY USER
    V_WEEKDAY_RESULT NUMBER;
BEGIN
    V_START_DATE := TRUNC(ADD_MONTHS(V_DATE_01,1),'MONTH');
    V_END_DATE := LAST_DAY(ADD_MONTHS(V_DATE_01,1));
    
    CASE V_WEEKDAY_INPUT
        WHEN 'SUNDAY' THEN V_WEEKDAY_RESULT := 1;
        WHEN 'MONDAY' THEN V_WEEKDAY_RESULT := 2;
        WHEN 'TUESDAY' THEN V_WEEKDAY_RESULT := 3;
        WHEN 'WEDNESDAY' THEN V_WEEKDAY_RESULT := 4;
        WHEN 'THURSDAY' THEN V_WEEKDAY_RESULT := 5;
        WHEN 'FRIDAY' THEN V_WEEKDAY_RESULT := 6;
        WHEN 'SATURDAY' THEN V_WEEKDAY_RESULT := 7;
    END CASE;
    

    WHILE V_START_DATE <= V_END_DATE -- BEGINS FROM FIRST DAY OF NEXT MONTH (ALSO IT IS POSSIBLE TO START 3RD WEEK START)
    LOOP

        IF TO_CHAR(V_START_DATE ,'D') = V_WEEKDAY_RESULT THEN -- IT STARTS COUNTING FROM SUNDAY
            V_RESULT_DATE := V_START_DATE; -- WHEN IT FINDS IT ASSIGNS VALUE TO V_RESULT_DATE
        END IF;
        
        IF TO_CHAR(V_START_DATE ,'D') = V_WEEKDAY_RESULT AND V_START_DATE != LAST_DAY(V_START_DATE) THEN
            V_RESULT_DATE2 := V_START_DATE; -- WHEN IT FINDS IT ASSIGNS VALUE TO V_RESULT_DATE2
        END IF;
        
        V_START_DATE := V_START_DATE + 1;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('INPUT DATE >> ' || V_DATE_01);
    DBMS_OUTPUT.PUT_LINE('V_RESULT_DATE >> ' || V_RESULT_DATE);
    DBMS_OUTPUT.PUT_LINE('V_RESULT_DATE2 >> ' || V_RESULT_DATE2);
END;
/
