-- FIRST THURSDAY BEFORE END OF NEXT MONTH (END OF NEXT MONTH IS NOT EXCLUDED/INCLUDED)
SELECT SYSDATE AS START_DATE
      ,CASE WHEN TO_CHAR(LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7 ,'D') = 5 THEN LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7  -- THURSDAY WE'RE LOOKING FOR
            ELSE NEXT_DAY(LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7 ,'THURSDAY')
      END AS FINAL_DATE -- LAST THURSDAY BEFORE END OF NEXT MONTH

      ,CASE WHEN TO_CHAR(LAST_DAY(ADD_MONTHS(TEST_DATE,1)) ,'D') = 5 THEN LAST_DAY(ADD_MONTHS(TEST_DATE,1))
            WHEN TO_CHAR(LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7 ,'D') = 5 THEN LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7  -- THURSDAY WE'RE LOOKING FOR
            ELSE NEXT_DAY(LAST_DAY(ADD_MONTHS(TEST_DATE,1)) - 7 ,'THURSDAY')      
      END AS FINAL_DATE2 -- LAST THURSDAY BEFORE END OF NEXT MONTH V2
FROM
(
SELECT TO_DATE('25082021' ,'DDMMYYYY') AS TEST_DATE
FROM DUAL
)
;
