SELECT A.*
        ,'XXX' AS SEPARATOR
        
        ,CASE WHEN QUARTER_03 IS NOT NULL THEN EXTRACT(YEAR FROM QUARTER_03) || ' Q' || TO_CHAR(QUARTER_03, 'Q') END AS QUARTER_03_F
        ,EXTRACT(YEAR FROM QUARTER_02) || ' Q' || TO_CHAR(QUARTER_02, 'Q') AS QUARTER_02_F
        ,EXTRACT(YEAR FROM QUARTER_01) || ' Q' || TO_CHAR(QUARTER_01, 'Q') AS QUARTER_01_F
        ,CASE WHEN END_OF_QUARTER_FLAG = 1 THEN EXTRACT(YEAR FROM REPORT_DATE) || ' Q' || TO_CHAR(REPORT_DATE, 'Q') ELSE INITCAP(TO_CHAR(REPORT_DATE, 'YYYY MON', 'NLS_DATE_LANGUAGE = ENGLISH')) END AS REPORT_DATE_F
FROM
    (
    SELECT END_OF_QUARTER_FLAG
            ,CASE WHEN END_OF_QUARTER_FLAG = 1 THEN QUARTER_03_Q ELSE QUARTER_03_M END AS QUARTER_03
            ,CASE WHEN END_OF_QUARTER_FLAG = 1 THEN QUARTER_01_Q ELSE QUARTER_02_M END AS QUARTER_02
            ,CASE WHEN END_OF_QUARTER_FLAG = 1 THEN QUARTER_01_Q ELSE QUARTER_01_M END AS QUARTER_01
            ,REPORT_DATE
    FROM
        (
        SELECT DATES
                ,CASE WHEN ADD_MONTHS(TRUNC(DATES,'Q') -1, 3) = DATES THEN 1 ELSE 0 END AS END_OF_QUARTER_FLAG
                
                -- QUARTER SECTON
                ,NULL AS QUARTER_03_Q
                ,CASE WHEN TRUNC(DATES, 'YEAR') -1 = ADD_MONTHS(DATES, -3) THEN ADD_MONTHS(DATES, -6) ELSE TRUNC(DATES, 'YEAR') -1 END QUARTER_02_Q
                ,ADD_MONTHS(DATES, -3) AS QUARTER_01_Q
                
                ,'XXX' AS SEPARATOR
                
                -- MONTH SECTION
                ,CASE WHEN EXTRACT(MONTH FROM DATES) IN (10,11) THEN TRUNC(DATES, 'YEAR') -1 ELSE ADD_MONTHS(ADD_MONTHS(ADD_MONTHS(TRUNC(ADD_MONTHS(DATES,-3), 'Q') -1, 3), -3), -3) END AS QUARTER_03_M
                ,ADD_MONTHS(ADD_MONTHS(TRUNC(ADD_MONTHS(DATES, -3), 'Q') -1, 3), -3) AS QUARTER_02_M
                ,ADD_MONTHS(TRUNC(ADD_MONTHS(DATES, -3),'Q') -1, 3) AS QUARTER_01_M
                
                ,DATES AS REPORT_DATE
        FROM
            (
            SELECT ADD_MONTHS(LAST_DAY(ADD_MONTHS(ADD_MONTHS(TRUNC(SYSDATE, 'YEAR'),12),-1)), -(LEVEL-1) ) AS DATES
            FROM DUAL
            CONNECT BY LEVEL < 1000
            )
        )
    ) A
WHERE 1=1
    AND
    (
    QUARTER_01 > TO_DATE('31122017', 'DDMMYYYY')
    AND QUARTER_02 > TO_DATE('31122017', 'DDMMYYYY')
    AND NVL(QUARTER_03, TO_DATE('31122999', 'DDMMYYYY')) > TO_DATE('31122017', 'DDMMYYYY')
    )
;
