DECLARE
    AVG_OF_INTERVAL_REQUESTS NUMBER;
    AVG_OF_INTERVAL_REQUESTS_INTEGER NUMBER;
BEGIN

    SELECT AVG(DIFFERENCE), FLOOR(AVG(DIFFERENCE))
            INTO AVG_OF_INTERVAL_REQUESTS, AVG_OF_INTERVAL_REQUESTS_INTEGER
    FROM
        (
        SELECT A.*
                ,LAG(REQUEST_DATE) OVER (ORDER BY REQUEST_DATE) AS PREVIOUS_ROW
                ,REQUEST_DATE - LAG(REQUEST_DATE) OVER (ORDER BY REQUEST_DATE) AS DIFFERENCE
        FROM
            (
            SELECT DISTINCT REQUEST_DATE
            FROM USE_CASE_2
            ) A
        ) B
    WHERE 1=1
        AND PREVIOUS_ROW IS NOT NULL
    ;
    DBMS_OUTPUT.PUT_LINE('AVG_OF_INTERVAL_REQUESTS >> ' || AVG_OF_INTERVAL_REQUESTS);
    DBMS_OUTPUT.PUT_LINE('AVG_OF_INTERVAL_REQUESTS_INTEGER >> ' || AVG_OF_INTERVAL_REQUESTS_INTEGER);
END
;
/
