-- CREATING EMPTY TABLE
CREATE TABLE USE_CASE_2
(
LINE NUMBER,
REQUEST_DATE DATE,
DEPARTMENT_NAME VARCHAR2(20),
COMPLETION_DATE DATE
);
COMMIT;




INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (1,TO_DATE('20-MAR-2021','DD-MON-YYYY'),'Department A',TO_DATE('27-MAR-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (2,TO_DATE('23-MAR-2021','DD-MON-YYYY'),'Department A',TO_DATE('30-MAR-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (3,TO_DATE('03-MAY-2021','DD-MON-YYYY'),'Department A',TO_DATE('07-MAY-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (4,TO_DATE('11-MAY-2021','DD-MON-YYYY'),'Department C',TO_DATE('14-MAY-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (5,TO_DATE('14-MAY-2021','DD-MON-YYYY'),'Department B',TO_DATE('14-MAY-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (6,TO_DATE('18-MAY-2021','DD-MON-YYYY'),'Department D',TO_DATE('18-MAY-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (7,TO_DATE('19-MAY-2021','DD-MON-YYYY'),'Department D',TO_DATE('22-MAY-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (8,TO_DATE('20-MAY-2021','DD-MON-YYYY'),'Department E',TO_DATE('24-MAY-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (9,TO_DATE('20-MAY-2021','DD-MON-YYYY'),'Department B',TO_DATE('23-MAY-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (10,TO_DATE('21-MAY-2021','DD-MON-YYYY'),'Department C',TO_DATE('26-MAY-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (11,TO_DATE('23-JUN-2021','DD-MON-YYYY'),'Department D',TO_DATE('26-JUN-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (12,TO_DATE('04-JUL-2021','DD-MON-YYYY'),'Department A',TO_DATE('09-JUL-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (13,TO_DATE('09-JUL-2021','DD-MON-YYYY'),'Department A',TO_DATE('10-JUL-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (14,TO_DATE('12-JUL-2021','DD-MON-YYYY'),'Department E',TO_DATE('17-JUL-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (15,TO_DATE('15-JUL-2021','DD-MON-YYYY'),'Department A',TO_DATE('17-JUL-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (16,TO_DATE('19-JUL-2021','DD-MON-YYYY'),'Department E',TO_DATE('25-JUL-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (17,TO_DATE('23-JUL-2021','DD-MON-YYYY'),'Department B',TO_DATE('28-JUL-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (18,TO_DATE('24-JUL-2021','DD-MON-YYYY'),'Department B',TO_DATE('25-JUL-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (19,TO_DATE('26-JUL-2021','DD-MON-YYYY'),'Department C',TO_DATE('02-AUG-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (20,TO_DATE('10-AUG-2021','DD-MON-YYYY'),'Department B',TO_DATE('10-AUG-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (21,TO_DATE('17-AUG-2021','DD-MON-YYYY'),'Department C',TO_DATE('20-AUG-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (22,TO_DATE('18-AUG-2021','DD-MON-YYYY'),'Department A',TO_DATE('20-AUG-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (23,TO_DATE('20-AUG-2021','DD-MON-YYYY'),'Department D',TO_DATE('24-AUG-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (24,TO_DATE('26-AUG-2021','DD-MON-YYYY'),'Department C',TO_DATE('26-AUG-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (25,TO_DATE('04-SEP-2021','DD-MON-YYYY'),'Department B',TO_DATE('11-SEP-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (26,TO_DATE('09-SEP-2021','DD-MON-YYYY'),'Department B',TO_DATE('09-SEP-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (27,TO_DATE('11-SEP-2021','DD-MON-YYYY'),'Department D',TO_DATE('15-SEP-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (28,TO_DATE('12-SEP-2021','DD-MON-YYYY'),'Department A',TO_DATE('13-SEP-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (29,TO_DATE('20-SEP-2021','DD-MON-YYYY'),'Department D',TO_DATE('24-SEP-2021','DD-MON-YYYY'));
INSERT INTO USE_CASE_2 (LINE,REQUEST_DATE,DEPARTMENT_NAME,COMPLETION_DATE) VALUES (30,TO_DATE('28-SEP-2021','DD-MON-YYYY'),'Department E',TO_DATE('03-OCT-2021','DD-MON-YYYY'));
COMMIT;




-- STEP 1 >> REMOVING DUPLICATES AND ORDERING (SORTING) DATE ASCENDING
SELECT DISTINCT REQUEST_DATE
FROM USE_CASE_2
ORDER BY 1
;




-- STEP 2 >> FOR EVERY ROW WE NEED PREVIOUS ROW VALUE
SELECT A.*
        ,LAG(REQUEST_DATE) OVER (ORDER BY REQUEST_DATE) AS PREVIOUS_ROW
        ,REQUEST_DATE - LAG(REQUEST_DATE) OVER (ORDER BY REQUEST_DATE) AS DIFFERENCE
FROM
    (
    SELECT DISTINCT REQUEST_DATE
    FROM USE_CASE_2
    --ORDER BY 1 -- DUE TO USAGE OR LAG FUNCTION AND THERE IS NO NEED OF ORDERING AT THIS LEVEL ANY MORE
    ) A
;



-- STEP 3 >> FILTERING NULL VALUE (FIRST ROW IS NOT INCLUDED IN CALCULATION AS PREVIOUS EXAMPLES) AND CALCULATING AVERAGE
SELECT *
FROM
    (
    SELECT A.*
            ,LAG(REQUEST_DATE) OVER (ORDER BY REQUEST_DATE) AS PREVIOUS_ROW
            ,REQUEST_DATE - LAG(REQUEST_DATE) OVER (ORDER BY REQUEST_DATE) AS DIFFERENCE
    FROM
        (
        SELECT DISTINCT REQUEST_DATE
        FROM USE_CASE_2
        ) A
    ) B
WHERE 1=1
    AND PREVIOUS_ROW IS NOT NULL
;




-- STEP 4 (FINAL) >> CALCULATING THE AVERAGE
SELECT AVG(DIFFERENCE) AS AVG_OF_INTERVAL_REQUESTS
        ,FLOOR(AVG(DIFFERENCE)) AS AVG_OF_INTERVAL_REQUESTS_INTEGER
FROM
    (
    SELECT A.*
            ,LAG(REQUEST_DATE) OVER (ORDER BY REQUEST_DATE) AS PREVIOUS_ROW
            ,REQUEST_DATE - LAG(REQUEST_DATE) OVER (ORDER BY REQUEST_DATE) AS DIFFERENCE
    FROM
        (
        SELECT DISTINCT REQUEST_DATE
        FROM USE_CASE_2
        ) A
    ) B
WHERE 1=1
    AND PREVIOUS_ROW IS NOT NULL
;
